### PR TITLE
Fix to support gradle 6

### PR DESCRIPTION
**Pull request by ksa-real**

### CODE REVIEW

**Comment by ksa-real** [comment]
Related issue:
https://github.com/dorongold/gradle-task-tree/issues/37

**Comment by ksa-real** [comment]
@dorongold Can you please review and release. I'm trying to avoid the plugin forking.

**Comment by tsjensen** [comment]
Thank you @ksa-real ! 
@dorongold Please push the merge button for Gradle 6 support

**Comment by ksa-real** [comment]
Meanwhile I've pushed the artifact to my fork:
https://github.com/ksa-real/gradle-task-tree/packages/63385

**Comment by kristian** [comment]
Also needed here. @dorongold could you please merge this and release 1.5? Thanks so much!

**Comment by claudioantonio** [comment]
Also need here! @dorongold could you please merge this commit? Thanks!!!

**Comment by tekumara** [comment]
+1 for this to be merged

**Comment by tsjensen** [comment]
More than a month have now passed without a reaction from @dorongold. We must assume that he is no longer able to support this project. 😢

@ksa-real Since you have the working fork, would you mind [publishing it on the Gradle Plugin Portal](https://guides.gradle.org/publishing-plugins-to-gradle-plugin-portal/) for us? Using it from GitHub Packages is problematic because it requires authentication.

**Comment by dorongold** [comment]
Merged and released in version 1.5. Now available on Gradle plugin portal.
Thanks for the fix @ksa-real !
Sorry for the long delay.

**Pull request merged**
